dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

branches:
  only:
    - master

cache:
  directories:
    - "node_modules"

# before_script:
#   - npm install -g @angular/cli

script:
  - npm run build:lib
  - npm run test:lib
  - npm run build:prod

# after_success:
#   - npm public ./lib

notifications:
  email:
    on_failure: always
    on_success: change
