dist: trusty
sudo: false

language: node_js
node_js:
  - 17

branches:
  only:
    - main

before_script:
    - npm install -g firebase-tools

script:
  - npm run build:lib
  - npm run build
  - npm run cypress:verify
  - npm run cypress:run

after_success:
  - firebase deploy --token $firebase_token

notifications:
  email:
    on_failure: always
    on_success: change
